name: Release

on:
  push:
    tags:
    - '*'

jobs: 
  release:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Extract tag name
      id: tag
      run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}
      shell: bash

    - name: Build
      run: dotnet build --configuration Release /p:Version=${{ steps.tag.outputs.version }}
   
    - uses: papeloto/action-zip@v1
      with:
        files: bin/Debug/net472-windows/dist
        dest: release-${{ steps.tag.outputs.version }}.zip
    
    - name: Create Draft Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag.outputs.version }}
        release_name: ${{ steps.tag.outputs.version }}
        draft: true
        prerelease: false

    - uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./release-${{ steps.tag.outputs.version }}.zip
        asset_name: release-${{ steps.tag.outputs.version }}.zip
        asset_content_type: application/zip

    - uses: eregon/publish-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        release_id: ${{ steps.create_release.outputs.id }}
